name: 'Prototype validator'
description: 'tbd'
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  data-source-config:
    description: 'tbd'
    required: true
  data-type-config:
    description: 'tbd'
    required: true
  box-config:
    description: 'tbd'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
